apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: envread
  name: envread
  namespace: development
spec:
  replicas: 5
  selector:
    matchLabels:
      app: envdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: envdemo
    spec:
      volumes:
      - name: envread-volume
        configMap:
          name: envread-settings
      containers:
      - image: bbachin1/envdemo:v2
        name: app-ui
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
        volumeMounts:
          - name: envread-volume
            mountPath: /usr/share/nginx/html/envapp/assets/   
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: envread
  namespace: development
  labels:
    run: envread
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: envdemo
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: envread-settings
  namespace: development
data:
  app.config.json: |-
    {
      "name": "envapp",
      "version": "1.0.0",
      "environment": "Development",
      "basehref": "envapp",
      "backgroundColor": "black"
    }
